version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /api-service
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /consumer-service
    schedule:
      interval: weekly
